/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as InvoiceImport } from './routes/invoice'
import { Route as TrackingItemIdImport } from './routes/tracking/$itemId'

// Create/Update Routes

const InvoiceRoute = InvoiceImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => rootRoute,
} as any)

const TrackingItemIdRoute = TrackingItemIdImport.update({
  id: '/tracking/$itemId',
  path: '/tracking/$itemId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/invoice': {
      id: '/invoice'
      path: '/invoice'
      fullPath: '/invoice'
      preLoaderRoute: typeof InvoiceImport
      parentRoute: typeof rootRoute
    }
    '/tracking/$itemId': {
      id: '/tracking/$itemId'
      path: '/tracking/$itemId'
      fullPath: '/tracking/$itemId'
      preLoaderRoute: typeof TrackingItemIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/invoice': typeof InvoiceRoute
  '/tracking/$itemId': typeof TrackingItemIdRoute
}

export interface FileRoutesByTo {
  '/invoice': typeof InvoiceRoute
  '/tracking/$itemId': typeof TrackingItemIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/invoice': typeof InvoiceRoute
  '/tracking/$itemId': typeof TrackingItemIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/invoice' | '/tracking/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to: '/invoice' | '/tracking/$itemId'
  id: '__root__' | '/invoice' | '/tracking/$itemId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  InvoiceRoute: typeof InvoiceRoute
  TrackingItemIdRoute: typeof TrackingItemIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  InvoiceRoute: InvoiceRoute,
  TrackingItemIdRoute: TrackingItemIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/invoice",
        "/tracking/$itemId"
      ]
    },
    "/invoice": {
      "filePath": "invoice.tsx"
    },
    "/tracking/$itemId": {
      "filePath": "tracking/$itemId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
